Nav menu
IntranelConsulting/beakbox pull request #5
Opened 2022-09-13 00:17 UTC by LikaKoptyreva

Restructuring and redesigning

2022-09-18 19:57 UTC, philiprenich commented on src/scripts/main.js
>  console.clear();
This is an odd line to have in a production script.

2022-09-18 20:10 UTC, philiprenich requested changes
Will discuss various changes in person

2022-11-01 20:43 UTC, philiprenich requested changes
Few changes, overall looks good! Let's have a quick chat to go over a couple other things.

2022-11-01 20:43 UTC, philiprenich commented on src/_layouts/page.html
> +      <nav class="nav">
This class name is redundant to the element. If using the element by itself is too vague, `header > nav` may work instead or a clearer class name.

2022-11-01 20:43 UTC, philiprenich commented on src/scss/_base.scss
> +img:not(.nav *, .footer *, .blog-posts *),
If you change/remove the `<nav>` class name don't forget the corresponding CSS :)

2022-11-01 20:43 UTC, philiprenich commented on src/scss/_header.scss
> +    width: 80rem;
duplicate `width` property.

2022-11-01 20:43 UTC, philiprenich commented on src/scss/_header.scss
> +  input[type="checkbox"] {
Add a `cursor: pointer` style so sighted users can tell the element is clickable.

2022-11-01 20:43 UTC, philiprenich commented on src/scss/_header.scss
> +    &:checked ~ .nav__links {
Let's go over the nav in person. Easier to talk through a couple things.

2022-11-01 20:43 UTC, philiprenich commented on src/scss/main.scss
> +input.button,
There shouldn't be `input`s with a class of "button". Instead use an actual button or `type="button"` (and selector `input[type="button"]`

2022-11-01 20:43 UTC, philiprenich commented on src/scss/main.scss
> +input.button:hover,
input class here as well

2022-11-04 01:08 UTC, LikaKoptyreva commented on src/_layouts/page.html
> +      <nav class="main-nav">
I've decided to keep the class here but renamed it to "main-nav" - to keep using BEM and differentiate it from the nav element in the blog section (I might see if we can improve it in the next pr)

2022-11-04 01:14 UTC, LikaKoptyreva commented on src/scss/_base.scss
> +:is(a, button, input, textarea, summary) {
Checked browser compatibility of :is and it shouldn't cause any issues - if someone uses an older version of the browser that doesn't support :is, it shouldn't be an issue too (as far as I understand) as focus styles will fall back to the browser's default

2022-11-04 01:17 UTC, LikaKoptyreva commented on src/scss/_footer.scss
> +    justify-items: center;
Added this property to make the link area of the logo the same size as the logo

2022-11-04 01:22 UTC, LikaKoptyreva commented on src/scss/_footer.scss
> +
Added these properties to make the social media links' area the same size as the image

2022-11-04 02:17 UTC, philiprenich approved these changes

2022-11-04 02:20 UTC, merged